import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Graph from '../components/Graph'
import { getPrices } from './api/getprices'

type Price = {
  count: number
  min: number
  q25: number
  q50: number
  q75: number
  max: number
  mean: number
  std: number
}
type MainProps = {
  prices: Record<number, Price>
}

const Home: NextPage<MainProps> = (props: MainProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cryptomines.ninja">cryptomines.ninja!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.block}>
            <Graph prices={props.prices} />
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Donate: TODO
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { prices: await getPrices() } }
}

export default Home
