import type { NextPage, GetServerSideProps } from 'next'
import { useState, useRef, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BoxPlot from '../components/BoxPlot'
import { getPrices } from './api/getprices'
import LineGraph from '../components/LineGraph'

type Price = {
  count: number
  min: number
  q25: number
  q50: number
  q75: number
  max: number
  mean: number
  std: number
}
type MainProps = {
  prices: Record<number, Price>
}


const Home: NextPage<MainProps> = (props: MainProps) => {
  const [selectedMP, selectMP] = useState<number>(0)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cryptomines.ninja">cryptomines.ninja!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.block}>
            <BoxPlot prices={props.prices} boxClicked={selectMP} />
          </div>
        </div>

        {selectedMP !== 0 &&
          <div className={styles.grid}>
            <div className={styles.block}>
              <LineGraph mp={selectedMP} />
            </div>
          </div>
        }
      </main>

      <footer className={styles.footer}>
        Donate: 0xFE3B38864E3673f425EC4Cc5Cb8A367E0ff21d2e
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { prices: await getPrices() } }
}

export default Home
