import type { NextPage, GetServerSideProps } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BoxPlot from '../components/BoxPlot'
import { getPrices } from './api/getprices'
import { getFunding } from './api/fundingstatus'
import LineGraph from '../components/LineGraph'
import ProgressBar from '../components/ProgressBar'

type Price = {
  count: number
  min: number
  q25: number
  q50: number
  q75: number
  max: number
  mean: number
  std: number
}
type MainProps = {
  prices: Record<number, Price>
  funding: Record<string, number>
}


const Home: NextPage<MainProps> = (props: MainProps) => {
  const [selectedMP, selectMP] = useState<number>(0)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://cryptomines.ninja">cryptomines.ninja!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.block}>
            <BoxPlot prices={props.prices} boxClicked={selectMP} />
          </div>
          {selectedMP !== 0 &&
            <div className={styles.block}>
              <LineGraph mp={selectedMP} />
            </div>
          }
          <div className={styles.block}>
            <h2>Fund new features &rarr;</h2>
            <ProgressBar
              shortDescription={'Import All Marketplace Orders Since the Beginning of Time'}
              fullDescription={
                <p>
                  Scrape all marketplace logs and import everything into the database.<br></br>
                  Will allow for accurate historical data all the way since game start.<br></br>
                  Both historical graph and <span className={styles.code}>/api/gethistory</span> will provide this data.<br></br><br></br>
                  Send your donations to the following address to fund this feature:<br></br>
                  <span className={styles.code}>0xD905797fa8820061a3d7210E2215B809E64A4aaA</span>
                </p>
              }
              current={props.funding['0xD905797fa8820061a3d7210E2215B809E64A4aaA']}
              max={1}
            />
            <ProgressBar
              shortDescription={'Add a Filterable Real-Time Feed of Listed Workers'}
              fullDescription={
                <p>
                  Provide a live feed of all listed to the marketplace workers in real time.<br></br>
                  Will support filtering by MP and/or max/min price as well as audible notifications.<br></br>
                  Manual purchasing of workers from the live feed right on this page will be available when this feature is realed.<br></br>
                  Automatic purchasing will be available at a later date.<br></br><br></br>
                  Send your donations to the following address to fund this feature:<br></br>
                  <span className={styles.code}>0x60A93CC037Db063aeaA659029040a7cc59Cc0293</span>
                </p>
              }
              current={props.funding['0x60A93CC037Db063aeaA659029040a7cc59Cc0293']}
              max={5} />
          </div>
        </div>

        {/* <div className={styles.grid}>
          </div> */}
      </main>

      <footer className={styles.footer}>
        Donate: 0xFE3B38864E3673f425EC4Cc5Cb8A367E0ff21d2e
      </footer>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
  return { props: { prices: await getPrices(), funding: await getFunding() } }
}

export default Home
